// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Roster_Application.Data;

#nullable disable

namespace Roster_Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231002204004_CreateClientTable")]
    partial class CreateClientTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Roster_Application.Models.ClientModel", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientContactDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleID")
                        .HasColumnType("int");

                    b.Property<int>("TotalHours")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.HasIndex("ScheduleID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Roster_Application.Models.ScheduleModel", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("ScheduleFriTotHours")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleMonTotHours")
                        .HasColumnType("int");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleSatTotHours")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleSunTotHours")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleThurTotHours")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleTueTotHours")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleWedTotHours")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.ToTable("ScheduleModel");
                });

            modelBuilder.Entity("Roster_Application.Models.ClientModel", b =>
                {
                    b.HasOne("Roster_Application.Models.ScheduleModel", "ScheduleId")
                        .WithMany()
                        .HasForeignKey("ScheduleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleId");
                });
#pragma warning restore 612, 618
        }
    }
}
